### ISSUE TITLE
Add feature to switch tags

### ISSUE THREAD

**Issue by orkenstein** [filmustage/filmustage-script-markdown#1]
Implement a feature to switch tags on multiple typing (F1->F2->F3 should switch tag for selected text)
Now:
![2019-02-08 18 24 15](https://user-images.githubusercontent.com/1461936/52487502-d814a600-2bce-11e9-930e-5768d358692c.gif)

**Comment by eDubrovsky** [comment]
Nice idea! Added it in to-do

**Comment by eDubrovsky** [comment]
Done!
