### ISSUE TITLE
Automatically extract space-characters (trim a string)

### ISSUE THREAD

**Issue by orkenstein** [filmustage/filmustage-script-markdown#2]
Now:
![2019-02-08 18 38 45](https://user-images.githubusercontent.com/1461936/52488429-d815a580-2bd0-11e9-8f55-fcb067a3a435.gif)

Maybe some other special characters, like dots, commas, etc.

**Comment by eDubrovsky** [comment]
@orkenstein Done!

**Comment by orkenstein** [comment]
The whitespace (or other space character) must be pushed outside the tag:
```
[s][s]Some_text[s] -> 
[s]<selection>[s]Some_text</selection>[s] -> 
[s][s]<tag>Some_text</tag>[s]
```

**Comment by eDubrovsky** [comment]
Fix in new version.
