### ISSUE TITLE
Automatically extract article from the beginning of the tag

### ISSUE THREAD

**Issue by orkenstein** [filmustage/filmustage-script-markdown#4]
```
<tag>the gay<\tag>
```
Turns into:
```
the <tag>gay<\tag>
```
Same for a, the.

**Comment by eDubrovsky** [comment]
Fix in new version.

**Comment by orkenstein** [comment]
@eDubrovsky 
This might be an issue:
![2019-02-27 15 16 11](https://user-images.githubusercontent.com/1461936/53489634-bbb7ab00-3aa2-11e9-8c07-54cd576f7b3b.gif)

**Comment by eDubrovsky** [comment]
Fixed in 0.2.2
