### ISSUE TITLE
Bug with the end of line

### ISSUE THREAD

**Issue by andreikaralkou** [filmustage/filmustage-script-markdown#8]
![2019-03-05 19 06 08](https://user-images.githubusercontent.com/8004262/53818870-dba30f00-3f79-11e9-91a4-8d69e135b4e2.gif)

**Comment by andreikaralkou** [comment]
But it works well if select only part of the last word
![2019-03-05 19 08 23](https://user-images.githubusercontent.com/8004262/53818974-15741580-3f7a-11e9-8a0b-38ffe93207eb.gif)

**Comment by eDubrovsky** [comment]
Fixed in new version.
